CREATE NEW BRANCH ARCHZOTAC | bash_archmini,bash_zotac,hypr & systemd
1. Created for each arch system a dedicated folder to match unique
config styles.
2. Modified successfull hyprpaper config in autostart.conf and modified
as well the changeBackground.timer/service to change wallpaper hourly.
3. Delete spotify, neofetch and chromium from dotfiles

diff --git a/bash_archzotac/bash/aliases b/bash_archzotac/bash/aliases
--- a/bash_archzotac/bash/aliases
+++ b/bash_archzotac/bash/aliases
@@ -6,18 +6,18 @@ alias lt='eza --tree --level=2 --long --icons --git'
 alias lta='lt -a'
 alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
 alias cd="zd"
-zd() {
-  if [ $# -eq 0 ]; then
-    builtin cd ~ && return
-  elif [ -d "$1" ]; then
-    builtin cd "$1"
-  else
-    z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
-  fi
-}
-open() {
-  xdg-open "$@" >/dev/null 2>&1 &
-}
+# zd() {
+#   if [ $# -eq 0 ]; then
+#     builtin cd ~ && return
+#   elif [ -d "$1" ]; then
+#     builtin cd "$1"
+#   else
+#     z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+#   fi
+# }
+# open() {
+#   xdg-open "$@" >/dev/null 2>&1 &
+# }
 
 # Directories
 alias ..='cd ..'
@@ -47,5 +47,5 @@ alias arch="cd /mnt/ds923plus/andreas/arch"
 alias andreas="cd /mnt/ds923plus/andreas"
 alias syazi='sudo -E yazi'
 # ssh connections
-alias ds923plus="ssh -i ~/.ssh/archmini_ed25519 ledroot@ds923plus.fritz.box"
+alias ds923plus="ssh -i ~/.ssh/archzotac_ed25519 ledroot@ds923plus"
 
diff --git a/bash_archzotac/bash/functions b/bash_archzotac/bash/functions
--- a/bash_archzotac/bash/functions
+++ b/bash_archzotac/bash/functions
@@ -7,7 +7,7 @@ checkKeys=$(
   echo $?
 )
 # define the keys you want to load, include like this var=("firstkey" "secondkey" ...)
-keys2Load=("${HOME}/.ssh/archmini_ed25519")
+keys2Load=("${HOME}/.ssh/archzotac_ed25519")
 # validate if a running socket exist
 if [[ -z $SSH_AUTH_SOCK ]]; then
   echo "WARNING: Your ssh agent service is not up and running."
@@ -96,4 +96,17 @@ y() {
 	IFS= read -r -d '' cwd < "$tmp"
 	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
 	rm -f -- "$tmp"
+}
+
+zd() {
+  if [ $# -eq 0 ]; then
+    builtin cd ~ && return
+  elif [ -d "$1" ]; then
+    builtin cd "$1"
+  else
+    z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
+  fi
+}
+open() {
+  xdg-open "$@" >/dev/null 2>&1 &
 }
